### ISSUE TITLE
[BUG] Get Warnning while compiling YAML

### ISSUE THREAD

**Issue by holefrog** [mmakaay/esphome-yeelight_bs2#106] opened 2023-01-03 06:03 UTC
**Describe the bug**
Get Warnning while compiling YAML:
```
INFO Updating https://github.com/mmakaay/esphome-xiaomi_bslamp2@dev
WARNING The selected ESP-IDF framework version is not the recommended one. If there are connectivity or build issues please remove the manual version.
```

**To Reproduce**
1. esphome run mydevice.yaml

**Additional context**

Compile from ESPHOME CLI, cause HA run on Raspberry Pi does not have  the required package
```
** Problem **:
...
...
Processing bedside-lamp (board: esp32doit-devkit-v1; framework: espidf; platform: platformio/espressif32 @ 3.5.0)
--------------------------------------------------------------------------------
Tool Manager: Installing espressif/toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch2
INFO Installing espressif/toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch2
Error: Could not find the package with 'espressif/toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch2' requirements for your system 'linux_aarch64'
======== [ERROR] /config/esphome/bedside-lamp.yaml ========
```

**Comment by mmakaay** [comment] 2023-01-05 14:39
The use of an older version of the ESP-IDF framework is a conscious choice here.
With the recommended framework version, the lamp will not work.
See this issue for details: https://github.com/mmakaay/esphome-xiaomi_bslamp2/issues/104
So the warning can be ignored here.

The other issue that you mention is a duplicate of: https://github.com/mmakaay/esphome-xiaomi_bslamp2/issues/63

**Closed as completed** 2023-01-23 22:51 UTC
